"""Committed, hash-gated LLM observations for the Then-and-Now roll-up.

The verdict and every number are computed in thennow.py and are authoritative.
This layer adds one or two sentences of plain commentary per node, generated by
Claude Haiku and CACHED in data/thennow_observations.json keyed by a stable
shape-hash, so a rebuild only calls the model when a node's qualitative state
actually shifts (rare, which is what makes the cache committable). With no key or
on a failed call, thennow.obs_fallback stands in, so a build never blocks on the
network. Mirrors the paced, cached, degrade-gracefully pattern in buzz.py.
"""

import json
import os
import urllib.error
import urllib.request

from .thennow import OBS_PATH, compute_thennow, obs_hash

LLM_MODEL = "claude-haiku-4-5-20251001"


def _load():
    try:
        return json.loads(OBS_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def _save(cache):
    OBS_PATH.parent.mkdir(parents=True, exist_ok=True)
    OBS_PATH.write_text(json.dumps(cache, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _prompt(node):
    checks = "; ".join(
        f"{c['name']} {'ok' if c['pass'] else 'FAILS'} ({c['detail']})"
        for c in (node.get("validation") or {}).get("checks", []))
    verdict = ("fits the dot-com rise-peak-fall analogy" if node.get("valid")
               else "does NOT fit the analogy, so its projection is suppressed")
    beyond = (" Its AI reading has already passed the dot-com peak level."
              if node.get("beyondDotcomPeak") else "")
    return (
        "You are annotating one metric on a page that compares the AI boom to the "
        "dot-com bubble (which peaked 2000-03-10). Write one or two sentences of "
        "plain, candid commentary on what THIS metric says about the comparison, "
        "plus one caveat a skeptical reader should keep in mind. Do not restate the "
        "projected date as a prediction; it is an analogy, not a forecast. Style: no "
        "em-dashes (use commas or periods), no bold, straight quotes only, no filler "
        "like 'notably' or 'it is worth noting'. Under 45 words.\n\n"
        f"Metric: {node.get('label')}\n"
        f"Verdict: {verdict}\n"
        f"Checks: {checks}\n"
        f"Current AI reading: {node.get('display')} "
        f"({round((node.get('intensityNow') or 0) * 100)}% of the dot-com peak intensity).\n"
        f"Equivalent dot-com date: {node.get('equivalentDotcomDate')} ({node.get('phase')}), "
        f"{node.get('daysFromPeak')} days from the 2000 peak; compression ratio "
        f"{node.get('compression')}.\n"
        f"Analogy-projected top: {node.get('projectedPeakDate')}.{beyond}"
    )


def _llm_observation(node):
    """One or two sentences from Haiku, or None (no key / error) to fall back."""
    key = os.environ.get("ANTHROPIC_API_KEY")
    if not key:
        return None
    body = json.dumps({
        "model": LLM_MODEL, "max_tokens": 200,
        "messages": [{"role": "user", "content": _prompt(node)}],
    }).encode("utf-8")
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages", data=body,
        headers={"x-api-key": key, "anthropic-version": "2023-06-01",
                 "content-type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=40) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        text = "".join(b.get("text", "") for b in data.get("content", [])).strip()
        return text or None
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError, KeyError, ValueError) as e:
        print(f"observation LLM failed ({node.get('key')}): {e}")
        return None


def refresh_observations(conn):
    """Regenerate only the nodes whose shape-hash changed, then write the cache.
    Safe to call every run: a no-op (no network) when nothing shifted or no key."""
    t = compute_thennow(conn)
    if not t:
        return 0
    cache = _load()
    changed = 0

    def walk(node):
        nonlocal changed
        if not node.get("wip"):
            h = node.get("obsHash") or obs_hash(node)
            entry = cache.get(node["key"])
            if not entry or entry.get("hash") != h:
                text = _llm_observation(node)
                if text:
                    cache[node["key"]] = {"hash": h, "text": text}
                    changed += 1
        for c in node.get("children", []):
            walk(c)

    walk(t["tree"])
    if changed:
        _save(cache)
    return changed
