"""Valuation multiple: the Shiller CAPE, comparable in absolute terms across
eras, so it reads "how expensive" beside price appreciation's "how far"."""

METRIC = {
    "key": "valuation_multiple", "label": "Valuation multiple", "parent": "valuation", "order": 20,
    "kind": "cape", "source": ("cape", None),
    "formula": lambda r: r["cape"], "cadence": "monthly",
    "type": "absolute_level", "direction": "up", "unit": "shiller_cape",
    "unitLabel": "CAPE",
    "ir": {
        "group": "tn_cape", "group_name": "Valuation multiple (WIP)", "foreign_from": "CAPE",
        "assets": [
            {
                "id": "raw.multpl_cape", "group": "tn_cape", "layer": "source", "status": "live",
                "name": "raw.multpl_cape", "mat": "HTML table", "cadence": "on generate",
                "dagster": "thennow/multpl_cape", "dbt": "source('multpl','shiller_pe')",
                "grain": "one HTML document (monthly CAPE table)",
                "why": "The valuation-multiple tap: Shiller CAPE, comparable in absolute terms across eras. Wholly separate from the price chain.",
                "desc": "multpl.com's public 'Shiller PE by month' table (Robert Shiller's data), parsed with the stdlib. No key. oracle/sources/cape.py.",
                "upstream": [],
                "transforms": [{"tag": "extract", "text": "HTTP GET + regex parse of the monthly table"}],
                "cardinality": "one document, ~1,800 monthly rows back to the 1870s.",
            },
            {
                "id": "cape_history", "group": "tn_cape", "layer": "raw", "status": "live",
                "name": "cape_history", "mat": "table · upsert", "cadence": "on generate",
                "dagster": "thennow/cape_history", "dbt": "cape_history",
                "grain": "one row per month",
                "why": "The parsed CAPE series, persisted with a committed CSV as fallback.",
                "desc": "date + CAPE, kept from 1990 on, upserted on date. oracle/sources/cape.py round-trip, data/cape_history.csv.",
                "upstream": ["raw.multpl_cape"],
                "schema": [
                    {"col": "date", "type": "TEXT", "kind": "key", "ex": "2000-03-01"},
                    {"col": "cape", "type": "REAL", "kind": "pass", "ex": {"live": "peak"}, "note": "smoothed peak shown"},
                ],
                "transforms": [
                    {"tag": "parse", "text": "'Mon D, YYYY' → month-start iso; keep ≥ 1990"},
                    {"tag": "incremental", "text": "upsert on date"},
                ],
                "tests": ["unique: date", "not_null: cape"],
                "cardinality": "~440 monthly rows (1990+).",
            },
            {
                "id": "stg_cape_filled", "group": "tn_cape", "layer": "staging", "status": "live",
                "name": "stg_cape_filled", "mat": "table", "cadence": "on generate",
                "dagster": "thennow/stg_cape_filled", "dbt": "stg_cape_filled",
                "grain": "one row per calendar day, per era window",
                "why": "Puts the monthly CAPE on the same gap-free daily grid as every other metric, so the roll-up can blend by day.",
                "desc": "Trims to the two era windows and forward-fills the published monthly value across its days (a step-hold, not interpolation). _grid + _fill.",
                "upstream": ["cape_history"],
                "schema": [
                    {"col": "era", "type": "STRING", "kind": "key", "ex": "ai"},
                    {"col": "date", "type": "DATE", "kind": "key", "ex": "{{asOf}}"},
                    {"col": "cape", "type": "NUMERIC", "kind": "derived", "ex": {"live": "rawNow"}, "note": "forward-filled monthly"},
                ],
                "transforms": [
                    {"tag": "trim", "text": "to the declared era windows"},
                    {"tag": "forward-fill", "text": "hold each month's CAPE across its days"},
                ],
                "cardinality": "daily; {{dotWk}}+{{aiWk}} weekly points shipped.",
            },
            {
                "id": "int_cape_metric", "group": "tn_cape", "layer": "intermediate", "status": "live",
                "name": "int_cape_metric", "mat": "table", "cadence": "on generate",
                "dagster": "thennow/int_cape_metric", "dbt": "int_cape_metric",
                "grain": "one row per (era, day)",
                "why": "Applies the declared formula. For CAPE the metric input is the CAPE value itself.",
                "desc": "Registry: formula = cape, type = absolute_level.",
                "upstream": ["stg_cape_filled"],
                "schema": [
                    {"col": "date", "type": "DATE", "kind": "key", "ex": "{{asOf}}"},
                    {"col": "value", "type": "NUMERIC", "kind": "derived", "ex": {"live": "rawNow"}, "note": "= cape"},
                ],
                "transforms": [{"tag": "formula", "text": "value = cape"}],
                "cardinality": "1:1 with the daily grid.",
            },
            {
                "id": "int_cape_smoothed", "group": "tn_cape", "layer": "intermediate", "status": "live",
                "name": "int_cape_smoothed", "mat": "table", "cadence": "on generate",
                "dagster": "thennow/int_cape_smoothed", "dbt": "int_cape_smoothed",
                "grain": "one row per (era, day)",
                "why": "The same centered mean as every metric, so the smoothing option is uniform.",
                "desc": "Centered moving average (edge-truncated at today), materialized at the 90-day '3-month' default and 30-day '1-month' windows; toggled in the page's Options drawer.",
                "upstream": ["int_cape_metric"],
                "schema": [
                    {"col": "date", "type": "DATE", "kind": "key", "ex": "{{asOf}}"},
                    {"col": "smoothed", "type": "NUMERIC", "kind": "derived", "ex": {"live": "smNow"}, "note": "now; smoothed peak ≈ {{peak}}"},
                ],
                "transforms": [{"tag": "smooth", "text": "centered 90-day mean"}],
                "tests": ["not_null: smoothed"],
                "cardinality": "1:1 with the daily grid.",
            },
            {
                "id": "int_cape_intensity", "group": "tn_cape", "layer": "intermediate", "status": "live",
                "name": "int_cape_intensity", "mat": "table", "cadence": "on generate",
                "dagster": "thennow/int_cape_intensity", "dbt": "int_cape_intensity",
                "grain": "one row per (era, day)",
                "why": "Maps CAPE onto the shared 0–1 intensity by ABSOLUTE level (a P/E means the same in any era).",
                "desc": "absolute_level: intensity = (cape − dot-com start cape) / (dot-com peak cape − start). AI keeps its absolute level, so a high starting CAPE reads as high intensity. _normalize.",
                "upstream": ["int_cape_smoothed"],
                "schema": [
                    {"col": "date", "type": "DATE", "kind": "key", "ex": "{{asOf}}"},
                    {"col": "progress", "type": "NUMERIC", "kind": "derived", "ex": "days ÷ ramp × 100"},
                    {"col": "intensity", "type": "NUMERIC", "kind": "derived", "ex": {"live": "intensity"}, "note": "0 start, 1 peak"},
                ],
                "transforms": [{"tag": "normalize", "text": "absolute level on the dot-com CAPE range"}],
                "tests": ["not_null: intensity"],
                "cardinality": "1:1; weekly-downsampled for the page.",
            },
            {
                "id": "int_cape_validated", "group": "tn_cape", "layer": "intermediate", "status": "live",
                "name": "int_cape_validated", "mat": "table", "cadence": "on generate",
                "dagster": "thennow/int_cape_validated", "dbt": "int_cape_validated",
                "grain": "one verdict per metric (+ one row per check)",
                "why": "The same gate as price, run independently on CAPE. Earns a projection only if CAPE rises, peaks, and falls like the dot-com reference with AI below that peak and rising.",
                "desc": "Two passes over CAPE's daily curves: candidacy then shape. Emits {valid, checks[], observations}; the verdict and numbers are computed, a cached hash-gated Haiku call writes the prose (deterministic fallback). _validate + observe.refresh_observations.",
                "upstream": ["int_cape_intensity"],
                "schema": [
                    {"col": "check", "type": "TEXT", "kind": "key", "ex": "rise, peak, fall"},
                    {"col": "pass", "type": "BOOLEAN", "kind": "derived", "ex": {"live": "valid"}, "note": "{{checksPass}}/{{checksN}} checks pass → {{verdictWord}}"},
                    {"col": "observations", "type": "TEXT", "kind": "derived", "ex": "Haiku · cached", "note": "{{obs}}"},
                ],
                "transforms": [
                    {"tag": "validate", "text": "candidacy + shape checks → verdict"},
                    {"tag": "observe", "text": "cached, hash-gated Haiku prose (deterministic fallback)"},
                ],
                "tests": ["not_null: valid", "accepted_values: valid in (true, false)"],
                "cardinality": "1 verdict per metric; gates the projection downstream.",
            },
            {
                "id": "graph.valuation_multiple", "group": "tn_cape", "layer": "serve", "status": "live",
                "name": "graph: valuation_multiple", "mat": "exposure (JSON)", "cadence": "on generate",
                "dagster": "thennow (exposure)", "dbt": "exposure: valuation_multiple",
                "grain": "one leaf block on thennow.html",
                "why": "The graph the reader sees: today's CAPE matched to a dot-com date and rate-scaled.",
                "desc": "Same _evaluate() + _emit() as price. CAPE reads LATE (near the 2000 peak), the deliberate counterweight to price appreciation. Ships the native CAPE for look-through. Projection drawn only if int_cape_validated conforms.",
                "upstream": ["int_cape_validated"],
                "json": "{ \"intensityNow\": {{intensity}}, \"equivalentDotcomDate\": \"{{equiv}}\",\n  \"daysFromPeak\": {{daysFromPeak}}, \"projectedPeakDate\": \"{{proj}}\",\n  \"capeNow\": {{rawNow}}, \"display\": \"{{display}}\" }",
                "transforms": [
                    {"tag": "lookup", "text": "value-match on the dot-com ramp"},
                    {"tag": "rate-scale", "text": "→ projected top"},
                    {"tag": "downsample", "text": "daily scalars + weekly plot series"},
                ],
                "cardinality": "one leaf node on the Then-and-Now page.",
            },
        ],
        "graph": {"vchain": {
            "ids": ["raw.multpl_cape", "cape_history", "stg_cape_filled", "int_cape_metric",
                    "int_cape_smoothed", "int_cape_intensity", "int_cape_validated", "graph.valuation_multiple"],
            "shorts": {"graph.valuation_multiple": "graph: valuation multiple"},
        }},
        "source_info": {
            "blurb": "Valuation multiple (WIP): a Then-and-Now leaf on its own daily pipeline, wholly separate from price. Shiller CAPE, comparable in absolute terms across eras, so it reads 'how expensive'. AI's CAPE is already near the 2000 peak, so this leaf reads late.",
            "options": [
                {"t": "Smoothing window", "d": "The same centered daily moving average as every metric (90-day default)."},
            ],
            "ambiguities": [
                {"t": "Absolute vs relative", "d": "Unlike price, CAPE is compared by absolute level (a P/E means the same in any era), so AI's high starting valuation shows up as high intensity rather than being normalized away."},
            ],
            "caveats": [
                {"t": "WIP prototype", "d": "Method and copy will change. Direct URL only."},
                {"t": "Parsed from multpl.com", "d": "The public 'Shiller PE by month' table (Robert Shiller's data), parsed with the stdlib, kept as a committed CSV fallback. Broad-market CAPE, not Nasdaq-specific."},
                {"t": "Validated and annotated", "d": "The same two-pass validator + cached Haiku observation as every metric, run independently on CAPE. The verdict and numbers are computed; the prose is layered on top and regenerates only when the analogy state shifts."},
            ],
            "cardinality": [
                {"asset": "raw.multpl_cape", "count": "1 doc", "meaning": "The monthly CAPE table, back to the 1870s."},
                {"asset": "cape_history", "count": "~440", "meaning": "Parsed monthly CAPE from 1990 on, committed to data/cape_history.csv."},
                {"asset": "stg_cape_filled", "count": "{{dotWk}}+{{aiWk}}", "meaning": "Monthly CAPE forward-filled onto the shared daily grid (weekly points shipped)."},
                {"asset": "int_cape_intensity", "count": "1:1", "meaning": "CAPE mapped to 0–1 intensity by absolute level on the dot-com range."},
                {"asset": "int_cape_validated", "count": "1 verdict", "meaning": "{{checksN}} checks → {{verdictLong}}."},
                {"asset": "graph.valuation_multiple", "count": "1 leaf", "meaning": "The projected top for the CAPE leaf."},
            ],
        },
    },
}
